import turtle
turtle.register_shape("tenor.gif")
turtle.addshape("tenor.gif")
turtle.shape("tenor.gif")
# turtle.forward(200)
# turtle.right(45)
# turtle.forward(100)
# turtle.right(90)
# turtle.forward(100)
turtle.speed(0)
turtle.tracer(100)
while True:
	turtle.left(0.5)
	turtle.pendown()
	turtle.right(45)
	turtle.forward(200)
	turtle.right(45)
	turtle.forward(100)
	turtle.right(90)
	turtle.forward(50)
	turtle.penup()
	turtle.goto(0,0)
turtle.mainloop()
